### PR TITLE
Fix deprecation notices about converting Hash into keyword arguments

### LINKED ISSUE #48: Warnings about deprecation of using the last argument as keyword arguments in Ruby 2.7
## What did you do?

Used gem with Ruby 2.7.

## What did you expect to happen?

Everything should work.

## What actually happened?

Everything worked as expected but I saw warnings about the deprecation of using the last argument as keyword arguments.

## Additional context

```
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:30: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:36: warning: The called method `load_from_file' is defined here
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:31: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:47: warning: The called method `load_from_secrets' is defined here
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:32: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:53: warning: The called method `load_from_credentials' is defined here
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/rails/config.rb:33: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/storkvist/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/anyway_config-2.0.0.pre2/lib/anyway/config.rb:188: warning: The called method `load_from_env' is defined here
```

## Environment

**Ruby Version:** 2.7

**Framework Version (Rails, whatever):** 6.0.2.1

**Anyway Config Version:** 2.0.0.pre2

### PR DESCRIPTION
**Pull request by storkvist**
Change-Id: I05162bc511252304a89b80b78a0ad2ce264e4d47

## What is the purpose of this pull request?

Fixes #48

Remove warnings about using the last argument as keyword arguments.

## What changes did you make? (overview)

Convert hash to keyword arguments in several method calls.

## Checklist

- [ ] I've added tests for this change
- [ ] I've added a Changelog entry
- [ ] I've updated a documentation

### CODE REVIEW

**Comment by palkan** [comment]
@storkvist Looks good! Thanks!

Could you please add Ruby 2.7 to the Build action matrix?

**Comment by storkvist** [comment]
> Could you please add Ruby 2.7 to the Build action matrix?

Yes, of course. Sorry, I missed that at first.

Also, I noticed [there are 2 linter errors](https://github.com/palkan/anyway_config/pull/49/checks?check_run_id=484263931#step:4:41) from `Lint/NonDeterministicRequireOrder`. Maybe I can fix them in my PR with adding `#sort`?

```ruby
Dir["#{File.dirname(__FILE__)}/support/**/*.rb"].sort.each { |f| require f }
```

Or should I leave it as is?

**Comment by palkan** [comment]
> Or should I leave it as is?

Let's leave. I'll take care of it later.

**Comment by palkan** [comment]
Thanks!

**Pull request merged**
